CREATE TABLE IF NOT EXISTS `dg_hud` (
  `identifier` VARCHAR(128) NOT NULL,
  `settings` TEXT NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
